server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      native:
        search-locations: file://${user.home}/Projects/Spring-Cloud-Config
      server:
        git:
#          uri: file:///Users/orsay0827/Projects/Spring-msa-config
          uri: https://github.com/junyoung1992/Spring-Cloud-Config.git
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh