drop table if exists member CASCADE;
create table member
(
/**
 * Java: Long == bigint
 * generated by default as identity: Null 값이 들어오면 고유값으로 채워줌
 */
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);