### 1-1. Sync 배치 호출
POST http://localhost:8080/batch
Content-Type: application/json

{
  "id": "1"
}

### 1-2. Async 배치 호출
POST http://localhost:8080/batch/async
Content-Type: application/json

{
  "id": "1"
}